export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD' 
export const SEARCH_ROBOT_PENDING = 'SEARCH_ROBOTS_PENDING'
export const SEARCH_ROBOT_SUCCESS = 'SEARCH_ROBOTS_SUCCESS'
export const SEARCH_ROBOT_FAILED = 'SEARCH_ROBOTS_FAILED'